spring:
  data:
    mongodb:
      username: keralakitchen
      password: keralakitchen
      host: 192.168.1.17
logging:
  file:
    name: logs/delivery-dev-app.log
#    path: logs/
  #pattern:
    console: "%d %-5level %logger : %msg%n"
#    console: %clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){yellow}
  #  file: "%d %-5level [%thread] %logger : %msg%n"
  level:
#    ROOT: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.controllers: DEBUG
    org.springframework.security: DEBUG
    #org.hibernate: DEBUG
    com.keralakitchen.delivery: DEBUG