server:
  servlet:
    context-path: /keralakitchen
spring:
  security:
    user:
      name: admin
      password: $2a$10$LAcnTld1x/LFDjFRU.sXzu2FKF3YtYIfPH5Kx5gGzLopsBq0uWQhC
  data:
    mongodb:
      authentication-database: admin
      database: KeralaKitchen
      port: 27017
springdoc:
  swagger-ui:
#    enabled: false
    disable-swagger-default-url: true
    query-config-enabled: true
    path: /docs
  api-docs:
#    enabled: true
    path: /v3/api-docs
    openapi: 3.1.0
    #version: openapi_3_0
logging:
  file:
#    path: logs/
    name: logs/delivery-app.log
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.controllers: INFO
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot.autoconfigure.security: INFO
    org.springframework.security: INFO
    org.mongodb.driver: INFO
    org.mongodb.SQL: INFO
    com.keralakitchen.delivery: INFO