spring:
  data:
    mongodb:
      username: keralakitchen
      password: keralakitchen
      host: 192.168.1.17
  logging:
    file: logs/delivery-app.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG