server:
  servlet:
    context-path: /keralakitchen
  port: 8090
spring:
  security:
    user:
      name: admin
      password: $2a$10$LAcnTld1x/LFDjFRU.sXzu2FKF3YtYIfPH5Kx5gGzLopsBq0uWQhC
#    ignoreList: /keralakitchen/docs/
    ignoreList: /resources/**,/static/**,/swagger-ui/**,/swagger-ui.html, /v3/api-docs/**,/docs/**,/css/**, /js/**, /images/**,/items/**
  data:
    mongodb:
      authentication-database: admin
      username: keralakitchen
      password: keralakitchen
      database: KeralaKitchen
      host: 192.168.1.17
      port: 27017
springdoc:
  swagger-ui:
#    enabled: false
#    enable-spring-security: false
    disable-swagger-default-url: true
    query-config-enabled: true
    path: /docs
  api-docs:
#    enabled: true
    path: /v3/api-docs
    openapi: 3.1.0
    #version: openapi_3_0
logging:
  file:
#    path: logs/
    name: logs/delivery-app.log
    console: "%d %-4level %logger : %msg%n"
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.controllers: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security: DEBUG
    org.mongodb.driver: ERROR
    org.mongodb.SQL: INFO
    com.keralakitchen.delivery: INFO